### ISSUE TITLE
Error while loading a Service Dialog

### ISSUE THREAD

**Issue by romanblanco** [ManageIQ/manageiq-automation_engine#129]
Lately I'm getting an error in Rails console while loading a Service Dialog. Not sure if it's issue in API or automate or somewhere else.

I don't know how exactly to reproduce this issue, but it happens a lot on the Dialog attached in the BZ https://bugzilla.redhat.com/show_bug.cgi?id=1518600.

Here's the error message:
```
F, [2017-12-08T14:47:44.897841 #27922] FATAL -- :                                                                                    
F, [2017-12-08T14:47:44.897964 #27922] FATAL -- : SystemStackError (stack level too deep):                                           
F, [2017-12-08T14:47:44.898034 #27922] FATAL -- :                                                                                    
F, [2017-12-08T14:47:44.898185 #27922] FATAL -- : /home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-automation_engine-a71f1de4e04f/lib/miq_automation_engine/engine/miq_ae_method_service.rb:2:in `const_missing'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-automation_engine-a71f1de4e04f/lib/miq_automation_engine/engine/miq_ae_method_service.rb:3:in `const_missing'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-automation_engine-a71f1de4e04f/lib/miq_automation_engine/engine/miq_ae_method_service.rb:3:in `const_missing'
...
...
...
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-automation_engine-a71f1de4e04f/lib/miq_automation_engine/engine/miq_ae_method_service.rb:3:in `const_missing'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-automation_engine-a71f1de4e04f/lib/miq_automation_engine/engine/miq_ae_method_service.rb:3:in `const_missing'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-automation_engine-a71f1de4e04f/lib/miq_automation_engine/engine/miq_ae_method_service.rb:3:in `const_missing'
activesupport (5.0.6) lib/active_support/inflector/methods.rb:270:in `const_get'
activesupport (5.0.6) lib/active_support/inflector/methods.rb:270:in `block in constantize'
activesupport (5.0.6) lib/active_support/inflector/methods.rb:266:in `each'
activesupport (5.0.6) lib/active_support/inflector/methods.rb:266:in `inject'
activesupport (5.0.6) lib/active_support/inflector/methods.rb:266:in `constantize'
activesupport (5.0.6) lib/active_support/inflector/methods.rb:311:in `safe_constantize'
activesupport (5.0.6) lib/active_support/core_ext/string/inflections.rb:77:in `safe_constantize'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-automation_engine-a71f1de4e04f/lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb:551:in `convert_value_based_on_datatype'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-automation_engine-a71f1de4e04f/lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb:276:in `process_args_attribute'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-automation_engine-a71f1de4e04f/lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb:259:in `block in process_args_as_attributes'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-automation_engine-a71f1de4e04f/lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb:259:in `each'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-automation_engine-a71f1de4e04f/lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb:259:in `process_args_as_attributes'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-automation_engine-a71f1de4e04f/lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_workspace_runtime.rb:140:in `instantiate'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-automation_engine-a71f1de4e04f/lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_workspace_runtime.rb:49:in `instantiate'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-automation_engine-a71f1de4e04f/lib/miq_automation_engine/engine/miq_ae_engine.rb:301:in `resolve_automation_object'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-automation_engine-a71f1de4e04f/lib/miq_automation_engine/engine/miq_ae_engine.rb:95:in `deliver'
app/models/resource_action.rb:80:in `deliver_to_automate_from_dialog_field'
app/models/dynamic_dialog_field_value_processor.rb:8:in `values_from_automate'
app/models/dynamic_dialog_field_value_processor.rb:3:in `values_from_automate'
app/models/dialog_field.rb:163:in `values_from_automate'
app/models/dialog_field_sorted_item.rb:104:in `raw_values'
app/models/dialog_field_sorted_item.rb:60:in `trigger_automate_value_updates'
app/models/dialog_field_serializer.rb:24:in `serialize'
app/models/dialog_group_serializer.rb:17:in `block in serialize_dialog_fields'
activerecord (5.0.6) lib/active_record/relation/delegation.rb:38:in `map'
activerecord (5.0.6) lib/active_record/relation/delegation.rb:38:in `map'
app/models/dialog_group_serializer.rb:16:in `serialize_dialog_fields'
app/models/dialog_group_serializer.rb:9:in `serialize'
app/models/dialog_tab_serializer.rb:16:in `block in serialize_dialog_groups'
activerecord (5.0.6) lib/active_record/relation/delegation.rb:38:in `map'
activerecord (5.0.6) lib/active_record/relation/delegation.rb:38:in `map'
app/models/dialog_tab_serializer.rb:15:in `serialize_dialog_groups'
app/models/dialog_tab_serializer.rb:9:in `serialize'
app/models/dialog_serializer.rb:16:in `block in serialize_dialog_tabs'
activerecord (5.0.6) lib/active_record/relation/delegation.rb:38:in `map'
activerecord (5.0.6) lib/active_record/relation/delegation.rb:38:in `map'
app/models/dialog_serializer.rb:15:in `serialize_dialog_tabs'
app/models/dialog_serializer.rb:22:in `block in serialize_dialogs'
app/models/dialog_serializer.rb:21:in `map'
app/models/dialog_serializer.rb:21:in `serialize_dialogs'
app/models/dialog_serializer.rb:9:in `serialize'
app/models/dialog.rb:111:in `content'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-api-462b79b228b4/app/controllers/api/service_dialogs_controller.rb:20:in `fetch_service_dialogs_content'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-api-462b79b228b4/app/controllers/api/base_controller/renderer.rb:268:in `fetch_direct_virtual_attribute'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-api-462b79b228b4/app/controllers/api/base_controller/renderer.rb:256:in `block in expand_virtual_attributes'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-api-462b79b228b4/app/controllers/api/base_controller/renderer.rb:252:in `each'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-api-462b79b228b4/app/controllers/api/base_controller/renderer.rb:252:in `expand_virtual_attributes'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-api-462b79b228b4/app/controllers/api/base_controller/renderer.rb:81:in `resource_to_jbuilder'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-api-462b79b228b4/app/controllers/api/base_controller/renderer.rb:17:in `render_resource'
/home/rblanco/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-api-462b79b228b4/app/controllers/api/base_controller.rb:91:in `show'
actionpack (5.0.6) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.6) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.6) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.6) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.6) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.6) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.6) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.6) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.6) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.6) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.6) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.6) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.6) lib/abstract_controller/base.rb:126:in `process'
actionpack (5.0.6) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.6) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.6) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.6) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.6) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.6) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.6) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.6) lib/action_dispatch/routing/route_set.rb:727:in `call'
secure_headers (3.0.3) lib/secure_headers/middleware.rb:10:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/cookies.rb:613:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.6) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.6) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.6) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.6) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.6) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.6) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
rack-mini-profiler (0.10.7) lib/mini_profiler/profiler.rb:282:in `call'
railties (5.0.6) lib/rails/engine.rb:522:in `call'
puma (3.7.1) lib/puma/configuration.rb:232:in `call'
puma (3.7.1) lib/puma/server.rb:578:in `handle_request'
puma (3.7.1) lib/puma/server.rb:415:in `process_client'
puma (3.7.1) lib/puma/server.rb:275:in `block in run'
puma (3.7.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by romanblanco** [comment]
@miq-bot add_label bug

**Comment by gmcculloug** [comment]
@d-m-u Can you try to reproduce this error with the suggested dialog?

@romanblanco Can you provide some details on the context in which you are using the dialog?  Is it connected to a Service order, Custom Button or Catalog Item?

**Comment by romanblanco** [comment]
@gmcculloug I've imported the dialog (Automate → Automation → Customization → Import/Export accordion) and tried to edit it in the Dialog Editor, it's not connected to any order, button or item.

**Comment by d-m-u** [comment]
I cannot reproduce this, but I do occasionally see errors close if I need to restart the server.

**Comment by gmcculloug** [comment]
@romanblanco This issue has always been the result of running Rails in development mode and modifying code for a model.  When Rails reloads the class it has the same name but the class object has a new `object_id` which ultimately causes the failure.  We do not have any accounts of this issue happening in production.

As @d-m-u mentioned above the only real solution is to restart the server.

Here is an example of how the class object gets updated in Rails dev mode:
```ruby
 [master x] ~/work/manageiq $ ber c
Loading development environment (Rails 5.0.6)
irb(main):001:0> a = Account.first
=> #<Account id: 1, name: "Test", acctid: nil, homedir: nil, local: nil, domain: nil, accttype: nil, vm_or_template_id: nil, display_name: nil, comment: nil, expires: nil, enabled: nil, last_logon: nil, host_id: nil>
```
Then comment out some methods in the `app/model/account.rb` file and save the file.

```ruby
irb(main):002:0> reload!
Reloading...
=> true
irb(main):003:0> b = Account.first
=> #<Account id: 1, name: "Test", acctid: nil, homedir: nil, local: nil, domain: nil, accttype: nil, vm_or_template_id: nil, display_name: nil, comment: nil, expires: nil, enabled: nil, last_logon: nil, host_id: nil>

irb(main):004:0> a.class.name
=> "Account"
irb(main):005:0> a.class.object_id
=> 70107371952440

irb(main):006:0> b.class.name
=> "Account"
irb(main):007:0> b.class.object_id
=> 70107299065540
irb(main):008:0> 
```

As you can see objects `a` and `b` are object say the are based on the `Account` class but each class object has a different `object_id`.

Running the same basic test but with Automate Service models reproduces the error:
```ruby
irb(main):002:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
=> #<MiqAeMethodService::MiqAeService:0x00007f83643a1e18 @drb_server_references=[], @inputs={}, @workspace=#<MiqAeEngine::MiqAeWorkspaceRuntime:0x00007f83643a20e8 @readonly=false, @nodes=[], @current=[], @datastore_cache={}, @class_methods={}, @dom_search=#<MiqAeEngine::MiqAeDomainSearch:0x00007f83643a1fa8 @fqns_id_cache={}, @fqns_id_class_cache={}, @partial_ns=[], @prepend_namespace=nil>, @persist_state_hash={}, @current_state_info={}, @state_machine_objects=[], @ae_user=nil, @rbac=false>, @persist_state_hash={}, @logger=#<Vmdb::Loggers::MulticastLogger:0x00007f8361858a18 @loggers=#<Set: {#<VMDBLogger:0x00007f8361858cc0 @level=1, @progname=nil, @default_formatter=#<Logger::Formatter:0x00007f8361858c20 @datetime_format=nil>, @formatter=#<VMDBLogger::Formatter:0x00007f8361858ab8 @datetime_format=nil>, @logdev=#<Logger::LogDevice:0x00007f8361858bd0 @shift_period_suffix="%Y%m%d", @shift_size=1048576, @shift_age=0, @filename=#<Pathname:/Users/gmccullough/work/manageiq/log/automation.log>, @dev=#<File:/Users/gmccullough/work/manageiq/log/automation.log>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x00007f8361858b80>>, @write_lock=#<Thread::Mutex:0x00007f8361858a68>, @local_levels={}>}>, @level=0>>

irb(main):003:0> a = $evm.vmdb('account').first
=> #<MiqAeServiceAccount:0x3fc1b21b1904 @object=#<Account id: 1, name: "Test", acctid: nil, homedir: nil, local: nil, domain: nil, accttype: nil, vm_or_template_id: nil, display_name: nil, comment: nil, expires: nil, enabled: nil, last_logon: nil, host_id: nil>, @virtual_columns=["href_slug", "region_description", "region_number"], @associations=["host", "vm_or_template"]>

irb(main):004:0> reload!
Reloading...
=> true

irb(main):005:0> b = $evm.vmdb('account').first
SystemStackError: stack level too deep
	from /Users/gmccullough/.gem/ruby/2.4.3/bundler/gems/manageiq-automation_engine-2b24b4e0421e/lib/miq_automation_engine/engine/miq_ae_method_service.rb:3:in `const_missing'
	from /Users/gmccullough/.gem/ruby/2.4.3/bundler/gems/manageiq-automation_engine-2b24b4e0421e/lib/miq_automation_engine/engine/miq_ae_method_service.rb:3:in `const_missing'
	from /Users/gmccullough/.gem/ruby/2.4.3/bundler/gems/manageiq-automation_engine-2b24b4e0421e/lib/miq_automation_engine/engine/miq_ae_method_service.rb:3:in `const_missing'
```

To work around this issue you'll need to restart the Rails server.

**Comment by romanblanco** [comment]
@gmcculloug Thanks for the explaination 👍

**Comment by romanblanco** [comment]
@fdupont-redhat :point_up: [January 22, 2018 11:23 AM](https://gitter.im/ManageIQ/manageiq?at=5a65bbb7ae53c159031b5e75)
