### ISSUE TITLE
Embedded Ansible erroring on 5.10.0.20

### ISSUE THREAD

**Issue by miha-plesko** [ManageIQ/manageiq-automation_engine#261]
Hey guys, Embedded Ansible is periodically failing for me on latest CFME appliance, putting following into evm.log:

```
[----] E, [2018-10-25T10:25:02.644473 #30085:338f88] ERROR -- : MIQ(ManageIQ::Providers::EmbeddedAnsible::AutomationManager::Refresher#refresh) EMS: [Embedded Ansible Automation Manager], id: [1000000000003] Unable to perform refre
sh for the following targets:
[----] E, [2018-10-25T10:25:02.644651 #30085:338f88] ERROR -- : MIQ(ManageIQ::Providers::EmbeddedAnsible::AutomationManager::Refresher#refresh)  --- ManageIQ::Providers::EmbeddedAnsible::AutomationManager [Embedded Ansible Automati
on Manager] id [1000000000003]
[----] I, [2018-10-25T10:25:02.657125 #30085:338f88]  INFO -- : MIQ(ManageIQ::Providers::EmbeddedAnsible::AutomationManager::Refresher#refresh) Refreshing all targets...Complete
[----] E, [2018-10-25T10:25:02.657456 #30085:338f88] ERROR -- : MIQ(MiqQueue#deliver) Message id: [1000000020918], Error: [undefined method `result_stdout' for #<AnsibleTowerClient::ProjectUpdate:0x0000000016318970>]
[----] E, [2018-10-25T10:25:02.657649 #30085:338f88] ERROR -- : [ManageIQ::Providers::BaseManager::Refresher::PartialRefreshError]: undefined method `result_stdout' for #<AnsibleTowerClient::ProjectUpdate:0x0000000016318970>  Metho
d:[block (2 levels) in <class:LogProxy>]
[----] E, [2018-10-25T10:25:02.657829 #30085:338f88] ERROR -- : /var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:67:in `refresh'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:11:in `refresh'
/var/www/miq/vmdb/app/models/ems_refresh.rb:103:in `block in refresh'
/var/www/miq/vmdb/app/models/ems_refresh.rb:102:in `each'
/var/www/miq/vmdb/app/models/ems_refresh.rb:102:in `refresh'
/var/www/miq/vmdb/app/models/miq_queue.rb:455:in `block in dispatch_method'
/usr/share/ruby/timeout.rb:93:in `block in timeout'
/usr/share/ruby/timeout.rb:33:in `block in catch'
/usr/share/ruby/timeout.rb:33:in `catch'
/usr/share/ruby/timeout.rb:33:in `catch'
/usr/share/ruby/timeout.rb:108:in `timeout'
/var/www/miq/vmdb/app/models/miq_queue.rb:453:in `dispatch_method'
/var/www/miq/vmdb/app/models/miq_queue.rb:430:in `block in deliver'
/var/www/miq/vmdb/app/models/user.rb:267:in `with_user_group'
/var/www/miq/vmdb/app/models/miq_queue.rb:430:in `deliver'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:104:in `deliver_queue_message'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:137:in `deliver_message'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:155:in `block in do_work'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:149:in `loop'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:149:in `do_work'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:329:in `block in do_work_loop'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:326:in `loop'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:326:in `do_work_loop'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:153:in `run'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:127:in `start'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:22:in `start_worker'
/var/www/miq/vmdb/app/models/miq_worker.rb:402:in `block in start_runner_via_fork'
/opt/rh/cfme-gemset/gems/nakayoshi_fork-0.0.4/lib/nakayoshi_fork.rb:23:in `fork'
/opt/rh/cfme-gemset/gems/nakayoshi_fork-0.0.4/lib/nakayoshi_fork.rb:23:in `fork'
/var/www/miq/vmdb/app/models/miq_worker.rb:400:in `start_runner_via_fork'
/var/www/miq/vmdb/app/models/miq_worker.rb:390:in `start_runner'
/var/www/miq/vmdb/app/models/miq_worker.rb:441:in `start'
/var/www/miq/vmdb/app/models/miq_worker.rb:271:in `start_worker'
/var/www/miq/vmdb/app/models/mixins/per_ems_worker_mixin.rb:74:in `start_worker_for_ems'
/var/www/miq/vmdb/app/models/mixins/per_ems_worker_mixin.rb:52:in `block in sync_workers'
/var/www/miq/vmdb/app/models/mixins/per_ems_worker_mixin.rb:51:in `each'
/var/www/miq/vmdb/app/models/mixins/per_ems_worker_mixin.rb:51:in `sync_workers'
/var/www/miq/vmdb/app/models/miq_server/worker_management/monitor.rb:53:in `block in sync_workers'
/var/www/miq/vmdb/app/models/miq_server/worker_management/monitor.rb:50:in `each'
/var/www/miq/vmdb/app/models/miq_server/worker_management/monitor.rb:50:in `sync_workers'
/var/www/miq/vmdb/app/models/miq_server/worker_management/monitor.rb:22:in `monitor_workers'
/var/www/miq/vmdb/app/models/miq_server.rb:339:in `block in monitor'
/opt/rh/cfme-gemset/bundler/gems/cfme-gems-pending-1ee45ac9278b/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/opt/rh/cfme-gemset/bundler/gems/cfme-gems-pending-1ee45ac9278b/lib/gems/pending/util/extensions/miq-benchmark.rb:28:in `realtime_block'
/var/www/miq/vmdb/app/models/miq_server.rb:339:in `monitor'
/var/www/miq/vmdb/app/models/miq_server.rb:380:in `block (2 levels) in monitor_loop'
/opt/rh/cfme-gemset/bundler/gems/cfme-gems-pending-1ee45ac9278b/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/opt/rh/cfme-gemset/bundler/gems/cfme-gems-pending-1ee45ac9278b/lib/gems/pending/util/extensions/miq-benchmark.rb:35:in `realtime_block'
/var/www/miq/vmdb/app/models/miq_server.rb:380:in `block in monitor_loop'
/var/www/miq/vmdb/app/models/miq_server.rb:379:in `loop'
/var/www/miq/vmdb/app/models/miq_server.rb:379:in `monitor_loop'
/var/www/miq/vmdb/app/models/miq_server.rb:241:in `start'
/var/www/miq/vmdb/lib/workers/evm_server.rb:27:in `start'
/var/www/miq/vmdb/lib/workers/evm_server.rb:48:in `start'
/var/www/miq/vmdb/lib/workers/bin/evm_server.rb:4:in `<main>'
```

**Comment by gmcculloug** [comment]
@jameswnl Do you think this is related to https://bugzilla.redhat.com/show_bug.cgi?id=1640533

**Comment by jameswnl** [comment]
@gmcculloug is there a BZ for this issue?

**Comment by gmcculloug** [comment]
I am not aware of any.

**Comment by jameswnl** [comment]
Confirmed with Tower folks, the `result_stdout` is removed from `project_update` in Tower 3.3
We'll have to get it from different endpoint `/api/v1/project_update/{id}/stdout/`

**Comment by bdunne** [comment]
@jameswnl The attribute is completely gone?

**Comment by jameswnl** [comment]
@bdunne can you help closing this one. already resolved by the merged PR.

**Comment by miha-plesko** [comment]
Allow me to do it, thanks for the fix :)
